name: C CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test-format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install -y gcc clang libcmocka-dev cmake make

            - name: Set up build directory
              run: mkdir -p build

            - name: Check formatting
              run: |
                  make clang-format

            - name: Build project
              run: |
                  make build-cli

            - name: Build and run tests
              run: |
                  make tests
